apiVersion: v1
kind: Service
metadata:
  name: {{ include "springbackendchart.fullname" . }}
  labels:
    {{- include "springbackendchart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "springbackendchart.selectorLabels" . | nindent 4 }}
